name: PiZYDS-KeepInventory
main: KeepInventory\Main
version: 1.0.0
api: [3.0.0,3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13,]
description: "Helps to Keep Inventory"
website: https://www.pizyds.com/
